[package]
name = "rust-websocket-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
serde = { version = "1.0.192", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
serde_json = "1"
diesel = { version = "2.1.3", features = ["postgres", "r2d2"] }
dotenv = "0.15"
rand = "0.8.5"
