services:
  sanctumchat-postgres:
    image: postgres:17
 #   cap_add: ["CAP_NET_BIND_SERVICE", "CAP_CHOWN"]
 #   cap_drop: ["ALL"]
    user: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sanctumchat_service
